import html2pdf from "html2pdf.js";

// Convert logo to Base64 for embedding
const getBase64Logo = async (url) => {
  const res = await fetch(url);
  const blob = await res.blob();
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result);
    reader.readAsDataURL(blob);
  });
};

export const exportPayslipPDF = async (payslipData) => {
  const {
    user,
    month,
    items = [],
    total_earnings,
    total_deductions,
    net_salary,
    created_by,
    currency,
  } = payslipData;

  const earnings = items.filter((i) => i.type === "earning");
  const deductions = items.filter((i) => i.type === "deduction");

  const logoSrc = await getBase64Logo(
    `${window.location.origin}/A8J3K9Z5QW/thalam-logo.png`
  );
  const formatMonth = (m) => {
    const [year, month] = m.split("-");
    return new Date(year, month - 1).toLocaleString("default", {
      month: "long",
      year: "numeric",
    });
  };

  const watermarkText = "THAALAM MEDIA GMBH";

  const element = document.createElement("div");
  element.innerHTML = `
    <div style="font-family: 'Segoe UI', sans-serif; padding: 40px; color: #333; position: relative;">
      <style>
        tr, td, th { page-break-inside: avoid !important; border-collapse: collapse; }
        .watermark {
          position: fixed;
          top: 50%;
          left: 50%;
          transform: translate(-50%, -50%);
          font-size: 60px;
          color: rgba(200,200,200,0.15);
          white-space: nowrap;
          z-index: 0;
          user-select: none;
        }
      </style>

      <div class="watermark"><img src="${logoSrc}" /></div>

      <div style="display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #ccc; padding-bottom: 15px;">
        <img src="${logoSrc}" alt="Company Logo" width="180" />
        <div style="text-align: right;">
          <h2 style="margin: 0;">Payslip for ${formatMonth(month)}</h2>
          <p style="margin: 0; font-size: 14px;">THAALAM MEDIA GMBH</p>
          <p style="margin: 0; font-size: 13px;">Talacker 41, Zürich</p>
        </div>
      </div>

      <div style="margin-top: 20px; font-size: 13px;">
        <div style="display: flex; justify-content: space-between;">
          <div>
            <p><strong>Employee Name:</strong> ${user?.name || "-"}</p>
            <p><strong>Email:</strong> ${user?.email || "-"}</p>
          </div>
          <div>
            <p><strong>Generated By:</strong> ${created_by || "-"}</p>
            <p><strong>Generated On:</strong> ${new Date().toLocaleDateString()}</p>
          </div>
        </div>
      </div>

      <div style="margin-top: 25px;">
        <h3 style="font-size: 14px; margin-bottom: 10px;">EARNINGS</h3>
        <table style="width: 100%; border: 1px solid #ccc; font-size: 12px;">
          <thead style="background-color: #333; color: white;">
            <tr>
              <th style="padding: 6px; text-align: left;">Component</th>
              <th style="padding: 6px; text-align: right;">Amount (${
                currency?.symbol || "₹"
              })</th>
            </tr>
          </thead>
          <tbody>
            ${
              earnings.length > 0
                ? earnings
                    .map(
                      (e) => `
              <tr>
                <td style="padding: 6px; border: 1px solid #ddd;">${
                  e.component_name
                }</td>
                <td style="padding: 6px; border: 1px solid #ddd; text-align: right;">
                  ${Number(e.amount || 0).toLocaleString("en-IN", {
                    minimumFractionDigits: 2,
                  })}
                </td>
              </tr>`
                    )
                    .join("")
                : `<tr><td colspan="2" style="text-align:center; padding: 8px;">No earnings found</td></tr>`
            }
            <tr style="background-color:#f5f5f5;">
              <td style="padding:6px; font-weight:bold;">Total Earnings</td>
              <td style="padding:6px; text-align:right; font-weight:bold;">
                ${currency?.symbol || "₹"} ${Number(
    total_earnings || 0
  ).toLocaleString("en-IN", { minimumFractionDigits: 2 })}
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div style="margin-top: 25px;">
        <h3 style="font-size: 14px; margin-bottom: 10px;">DEDUCTIONS</h3>
        <table style="width: 100%; border: 1px solid #ccc; font-size: 12px;">
          <thead style="background-color: #333; color: white;">
            <tr>
              <th style="padding: 6px; text-align: left;">Component</th>
              <th style="padding: 6px; text-align: right;">Amount (${
                currency?.symbol || "₹"
              })</th>
            </tr>
          </thead>
          <tbody>
            ${
              deductions.length > 0
                ? deductions
                    .map(
                      (d) => `
              <tr>
                <td style="padding: 6px; border: 1px solid #ddd;">${
                  d.component_name
                }</td>
                <td style="padding: 6px; border: 1px solid #ddd; text-align: right;">
                  ${Number(d.amount || 0).toLocaleString("en-IN", {
                    minimumFractionDigits: 2,
                  })}
                </td>
              </tr>`
                    )
                    .join("")
                : `<tr><td colspan="2" style="text-align:center; padding: 8px;">No deductions found</td></tr>`
            }
            <tr style="background-color:#f5f5f5;">
              <td style="padding:6px; font-weight:bold;">Total Deductions</td>
              <td style="padding:6px; text-align:right; font-weight:bold;">
                ${currency?.symbol || "₹"} ${Number(
    total_deductions || 0
  ).toLocaleString("en-IN", { minimumFractionDigits: 2 })}
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div style="margin-top: 30px; text-align:right;">
        <h3 style="margin:0; font-size:16px;">Net Salary: 
          <span style="color:green;">${currency?.symbol || "₹"} ${Number(
    net_salary || 0
  ).toLocaleString("en-IN", { minimumFractionDigits: 2 })}</span>
        </h3>
      </div>

      <div style="display: flex; justify-content: space-between; margin-top: 60px;">
        <div style="width: 45%;">
          <p style="font-size: 14px;"><strong>Prepared By:</strong></p>
          <div style="margin-top: 50px; border-top: 1px solid #000; width: 60%;"></div>
          <p style="margin-top: 4px; font-size: 12px;">Signature</p>
        </div>
        <div style="width: 45%; text-align: right;">
          <p style="font-size: 14px;"><strong>Employee Signature:</strong></p>
          <div style="margin-top: 50px; border-top: 1px solid #000; width: 60%; float: right;"></div>
          <p style="margin-top: 4px; font-size: 12px;">Signature</p>
        </div>
      </div>
    </div>
  `;

  html2pdf()
    .set({
      margin: 0.5,
      filename: `${user?.name || "Employee"}_Payslip_${month}.pdf`,
      html2canvas: { scale: 2, useCORS: true, scrollY: 0 },
      jsPDF: { unit: "in", format: "a4", orientation: "portrait" },
    })
    .from(element)
    .save();
};
